[package]
name = "spear"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ctrlc = "3.5.0"
ratatui = "0.29.0"
rltk = "0.8.7"
specs = "0.20.0"
specs-derive = "0.4.1"
